### ISSUE TITLE
Typo in git clone url in the ReadMe

### ISSUE THREAD

**Issue by harshssd** [good-parts/aws-bootstrap#4]
It is 
`git clone https://github.com/good-parts/aws-boostrap.git`

and should be
`git clone https://github.com/good-parts/aws-bootstrap.git`

**Comment by dvassallo** [comment]
Fixed, thank you! — This is still a work in progress, BTW. It's a fork of [this other project](https://github.com/dvassallo/github-to-ec2-pipeline), which is a bit more stable.
